scoreboard1:
  - '&f '
  - '&7Inhibitors: &6{onlinePlayers}&7/&6150'
  - '&7&m----------------&f '
  - '&c[Info]'
  - '&8>&7Rank: &6{pexRank}'
  - '&8>&7Level: &6{factionLevel}'
  - '&8>&7Balance: &6{playerBalance}'
  - '&8>&7Kills: &6{killCount} '
  - '&8>&7Deaths: &6{deathCount}'
  - '&7&m----------------'
  - '&c[Status]'
  - '&8>&7Votes: &6{voteCount}&7/&650'
  - '&8>&7TPS: &6{tps}'
