scoreboard1:
  - '&7&l? &bOnline: &f{onlinePlayers}'
  - '&7&l? &bName: &f{playerName}'
  - '&7&l? &bLevel: &f{factionLevel}'
  - '&7&l? &bRank: &f{pexRank}'
  - '&7&l? &bKills: &f{killCount}'
  - '&7&l? &bTokens: &f{stattrackTokens}'
  - '&7&l? &bBalance: &f{playerBalance}'
  - '&f '
  - '&7&l? &bDonate: &f/buy'
  - '&f '
  - '&7&l? &bTPS: &f{tps}'

scoreboard2:
  - '&7&l? &bOnline: &f{onlinePlayers}'
  - '&7&l? &bName: &f{playerName}'
  - '&7&l? &bLevel: &f{factionLevel}'
  - '&7&l? &bRank: &f{pexRank}'
  - '&7&l? &bKills: &f{killCount}'
  - '&7&l? &bTokens: &f{stattrackTokens}'
  - '&7&l? &bBalance: &f{playerBalance}'
  - '&f '
  - '&7&l? &bVote: &f/vote'
  - '&f '
  - '&7&l? &bTPS: &f{tps}'